---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.11.4
  - conda-forge::pip=23.1.2
  - conda-forge::setuptools=65.5.1
  - pip:
    - tensorflow==2.15.1
    - pvactools==5.3.1
    - git+https://github.com/griffithlab/bigmhc.git#egg=bigmhc
    - git+https://github.com/griffithlab/deepimmuno.git#egg=deepimmuno
    - mhcflurry==2.0.6
    - mhcgnomes==1.8.6
    - mhcnames==0.4.8
    - mhcnuggets==2.4.1
    - mhctools==1.9.0